### ISSUE TITLE
cmake version

### ISSUE THREAD

**Issue by mipac** [muellan/clipp#29]
cmake version 3.8 is too high for nothing
on debian, standard version is 3.7.?
I don't know for other distrib but I guess 3.8 is too high for most of them
perhaps someone could details the version of cmake on mainstream distrib, to help choosing a better version level :)

thx for that clever lib!

**Comment by muellan** [comment]
@heavywatal Could you check that? Does your CMakeList require version 3.8?

**Comment by heavywatal** [comment]
Yes, it does. The meta tag `cxx_std_11` was introduced in 3.8:
https://github.com/muellan/clipp/blob/2c32b2f1f7cc530b1ec1f62c92f698643bb368db/CMakeLists.txt#L12

This is how we declare C++11 with modern CMake, as suggested by @m-waka in https://github.com/muellan/clipp/pull/11#issuecomment-487585464 .
It properly propagates C++11 flag to other projects that import clipp as an interface library. I like this feature, and don't think CMake 3.8 is too new because for example,
- [3.13 seems to be provided by the official Debian repository for stable "buster" (and oldstable "stretch" as a backport)](https://packages.debian.org/en/buster/cmake).
- [3.9 has been successfully working on Travis CI (Ubuntu 14.04 Trusty)](https://docs.travis-ci.com/user/languages/cpp/#cmake). Now shift to 16.04 Xenial with 3.12 is in progress.
- [3.13 is provided for CentOS 7 via EPEL](https://centos.pkgs.org/7/epel-x86_64/cmake3-3.13.5-1.el7.x86_64.rpm.html).
- The latest version is available for macOS and Linux via Homebrew.

In summary, it should not be so hard to install a newer version even if the built-in CMake is too old. That being said, we have three options:
1. Require users to use a decent CMake (>= 3.8). Clean but harsh. The users on old OS may not be able to enjoy the CMake package system for clipp.
1. Drop requirements to >=3.2, stop using `cxx_std_11`, and manually list up the [C++11 features](https://cmake.org/cmake/help/v3.2/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html) used in clipp. Clean but cumbersome. It increases the size and maintenance cost of `CMakeLists.txt`.
1. Drop requirements to >=3.2, stop using `target_compile_features`, and go back to old-fashioned [`set(CMAKE_CXX_STANDARD 11)`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html). Easy but nasty. It may contaminate the other projects that import clipp.

**Comment by eyalroz** [comment]
Disagree with @mipac .

The current Debian release is 10.0, codename Buster - released this year. Its CMake version is 3.13.4 .

If you look at [this listing](https://unix.stackexchange.com/a/535074/34868), you'lll see that a minimum CMake version of 3.10 is quite safe except for CentOS (and of course, obsolete distribution releases). So 3.8 should be fine.

**Comment by mipac** [comment]
didn't though that it could be a big deal 😄

well, I just report that a mean user, like me, who clone that good library to use it in a stable distrib will have to up his cmake for a "not so important feature" (the way you declare c++11... really)

When you don't work alone and you can have the freedom to be up to date, it's not a good idea, except when there is a big advantage.

it's not a problem however, one can modify the version in the cmakefile, and comment a line, and everything is fine

I close, because I think that someone who find a way to solve that problem will find here enough informations

thanks for sharing that good lib 😉

**Comment by eyalroz** [comment]
@mipac : Building and installing your own version CMake is not that big of a deal (it's much easier than building a compiler). And if you're working on an old distribution, you probably want to do that for a bunch of packages.
