### ISSUE TITLE
Prefix free check seems broken

### ISSUE THREAD

**Issue by rob-p** [muellan/clipp#3]
The prefix free check doesn't seem to work (i.e., enabling it on various programs from the `examples` directory leads to failed assertions).  I'm not entirely sure why this happens, but at least one issue seems to be that `value` options, when encountered in the prefix_free check are parsed as the empty string, and therefore appear as a prefix of _everything else_.

**Comment by muellan** [comment]
You are right. Thanks for checking this. In a previous design iteration this wouldn't have happend. Now that value parameters and flagged parameters are basically the same under the hood values must of course be ignored for the prefix check.
I will fix it and add a small set of tests for this.

**Comment by muellan** [comment]
The latest commit should fix the basic functionality.

There was another issue that I totally forgot about. Sometimes you need the same flags in different "branches" of alternatives. Since they will usually not interfere with each other this should not be reported as an error ( - I think). I'm not sure if this was the right decision, but I changed it, so that if flags are identical it is not reported as non-prefix-free.

Maybe I should also add a function that returns a list of the conflicts and not just a bool.

**Comment by rob-p** [comment]
Hi @muellan ,

  Thanks for addressing this so quickly (very cool library btw!).  I agree that repeated options in different branches (e.g. in different sub-commands) should not be conflicted.  The way I was trying to handle this before was by running the prefix free check independently for each branch.  However, I think the behavior you mentioned sounds reasonable.
