### ISSUE TITLE
Is this repo still alive? Update: yes

### ISSUE THREAD

**Issue by whit2333** [muellan/clipp#59]
@muellan Is this project still being maintained? Seems like not much has happened on your side in the past 18 months?

**Comment by Radagan** [comment]
I'm wondering the same thing. I would like to use this library in a project, but I have concerns it is dead. There's a pull request that adds C++20 though.

**Comment by Toxe** [comment]
Wondering the same thing. I was running into some problems with C++20 and MSVC and even though I see a PR that might fix that I wonder if I should just abandon this (which would be a bummer because I quite like it) and look for something else.

**Comment by GerHobbelt** [comment]
after I pushed a few pullreqs I saw this issue. AFAICT no github activity since Q1 2020, but the man is still around it seems (his website is still active in Q1 2021, so keeping my options open 😄 

Anyway, it's a git repo so the beauty is you can always pick what you like and work on t hat, than see about merging it back later. (My fork, for example: https://github.com/GerHobbelt/clipp -- if you use that stuff, cool, but be reminded that I currently do not test the stuff on Linux: Windows dev only ATM, as this is a small item in a bigger work, so little time for platforms that don't have my focus right now)

**Comment by whit2333** [comment]
I have exchanged emails with @muellan  and he is still planning to maintain this library.
